Feature : follow
team-waff1e/Backend pull request #18
Opened 2023-10-26 08:37 UTC by peppermintt0504

## PR 체크사항
PR이 다음 사항을 만족하는지 확인해주세요.

- [ ] 커밋 메시지 작성 가이드라인
- [ ] 라벨, 담당자, 리뷰어 지정

## PR 타입
어떤 유형의 PR인지 체크해주세요.

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Documentation content changes
- [ ] Other... Please describe:

## PR 설명
follow 기능 추가

## 작업사항
- follow API
- unfollowAPI
- followList API

## 변경로직
-

2023-10-26 12:39 UTC, JehunYoo requested changes

2023-10-26 12:39 UTC, JehunYoo commented on src/main/java/io/github/teamwaff1e/waffle/domain/member/dao/MemberDao.java
> +
- follow 관련 메서드는 `FollowDao`로 분리해야할 것 같습니다.
- `unfollow`에 관한 DB 로직을 repository에서 수행하고 아래의 `unfollow` 메서드는 조건에 맞는 `Follow`를 가져오는 메서드와 삭제하는 메서드로 나누는 것은 어떨까요? (마찬가지로 follow 로직은 repository에서하고 DAO에서는 저장하는 메서드)

2023-10-26 12:39 UTC, JehunYoo commented on src/main/java/io/github/teamwaff1e/waffle/domain/member/entity/Follow.java
> +    protected Follow(long memberId,long followingId) {
`long` -> `Long`

2023-10-27 01:45 UTC, suakang17 commented on src/main/java/io/github/teamwaff1e/waffle/domain/member/entity/Follow.java
> +    public String toString(){
얘는 로그용인가요?

2023-10-31 04:49 UTC, peppermintt0504 commented on src/main/java/io/github/teamwaff1e/waffle/domain/member/dao/MemberDao.java
> +
@JehunYoo 분리 완료

2023-10-31 05:06 UTC, peppermintt0504 commented on src/main/java/io/github/teamwaff1e/waffle/domain/member/entity/Follow.java
> +    public String toString(){
@suakang17 넹 로그용입니다

2023-10-31 05:07 UTC, peppermintt0504 commented on src/main/java/io/github/teamwaff1e/waffle/domain/member/entity/Follow.java
> +    protected Follow(long memberId,long followingId) {
@JehunYoo 변경 완료

2023-10-31 05:11 UTC, JehunYoo approved these changes

2023-10-31 05:18 UTC, merged