단일 Waffle CRUD
team-waff1e/Backend pull request #4
Opened 2023-10-19 00:51 UTC by suakang17

## PR 체크사항
PR이 다음 사항을 만족하는지 확인해주세요.

- [x] 커밋 메시지 작성 가이드라인
- [x] 라벨, 담당자, 리뷰어 지정

## PR 타입
어떤 유형의 PR인지 체크해주세요.

- [ ] Bugfix
- [x] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Documentation content changes
- [ ] Other... Please describe:

## PR 설명
- 단일 Waffle(게시글)에 대한 CRUD 기능 추가
- Waffle `likes` field 로직 추가

## 작업사항
- 단일 Waffle 등록
- 단일 Waffle 조회
- 단일 Waffle 수정
- 단일 Waffle 삭제
- Waffle like, unlike

## 변경로직
- .

2023-10-19 04:24 UTC, peppermintt0504 approved these changes

2023-10-19 05:14 UTC, JehunYoo requested changes
`WaffleController` 변경이 필요합니다!

2023-10-19 05:14 UTC, JehunYoo commented on src/main/java/io/github/teamwaff1e/waffle/domain/waffle/controller/WaffleController.java
> +    public WaffleResponseDto updateWaffle(@ModelAttribute UpdateWaffleRequestDto updateWaffleRequestDto, @PathVariable String waffleId, BindingResult bindingResult) {
1. `@PathVariable String waffleId`가 이미 `UpdateWaffleRequestDto`에 포함되어 있는데 불필요하게 추가되어있습니다. (+ 사용해야한다면 `Long waffleId`로 변경해할 것 같습니다.)
2. `BindingResult bindingResult`는 항상 `bindingResult`의 타겟이 되는 `@ModelAttribute` 객체 바로 뒤에서 전달되어야 합니다.

2023-10-19 05:14 UTC, JehunYoo commented on src/main/java/io/github/teamwaff1e/waffle/domain/waffle/dto/request/CreateWaffleRequestDto.java
> +    private Long memberId;
`UpdateWaffleRequestDto`와 비교했을 때,
`@AllArgsConstructor`로 생성자를 만들게 되면 `content`와 `id`의 위치가 달라서 argument 위치도 달라집니다.
`RequestDto`라서 스프링이 controller로 자동으로 매핑해주기 때문에 큰 문제는 없지만 참고해주세요!

2023-10-19 07:29 UTC, JehunYoo requested changes

2023-10-19 07:29 UTC, JehunYoo commented on src/main/java/io/github/teamwaff1e/waffle/domain/waffle/dto/response/WaffleResponseDto.java
> +
1. `likes` Long 타입으로 수정해야할 것 같습니다.
2. `createdAt`, `updateAt` 도 추가해주면 좋을 것 같습니다. (createdAt: waffle 정렬 기준으로 사용, updatedAt: 최근 수정 날짜 표시에 사용)

2023-10-19 08:29 UTC, suakang17 commented on src/main/java/io/github/teamwaff1e/waffle/domain/waffle/dto/response/WaffleResponseDto.java
> +
1. api 명세가 임시었어서 Integer로 받아뒀었습니다! 명세와 함께 업데이트 하도록 하겠습니다.
2. ✅

2023-10-19 12:46 UTC, JehunYoo requested changes

2023-10-19 12:46 UTC, JehunYoo commented on src/main/java/io/github/teamwaff1e/waffle/domain/waffle/entity/Waffle.java
`Integer.MAX_VALUE` -> `Long`에 맞게 수정 필요합니다!

2023-10-19 13:26 UTC, suakang17 commented
난 왜 하나만 생각라고 둘은 생각을 안할까?
어케 이렇게 상세하게 짚어낼수 있는 코드리뷰를 하시나요
비법이 궁금해요

2023년 10월 19일 (목) 21:46, Jehun Yoo ***@***.***>님이 작성:

> ***@***.**** requested changes on this pull request.
> ------------------------------
>
> On
> src/main/java/io/github/teamwaff1e/waffle/domain/waffle/entity/Waffle.java
> <https://github.com/team-waff1e/Backend/pull/4#discussion_r1365447893>:
>
> Integer.MAX_VALUE -> Long에 맞게 수정 필요합니다!
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/team-waff1e/Backend/pull/4#pullrequestreview-1687583632>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AWI25QQT4KOJMWT3JE2FOXTYAEOJRAVCNFSM6AAAAAA6GLJYR6VHI2DSMVQWIX3LMV43YUDVNRWFEZLROVSXG5CSMV3GSZLXHMYTMOBXGU4DGNRTGI>
> .
> You are receiving this because you were assigned.Message ID:
> ***@***.***>
>

2023-10-20 02:54 UTC, JehunYoo approved these changes

2023-10-20 02:55 UTC, merged